### PR TITLE
Catch up replay to bridge's replay

### PR DESCRIPTION
**Pull request by VenelinMartinov**
Apply changes to replay from tf-bridge from https://github.com/pulumi/pulumi-terraform-bridge/pull/1496 and https://github.com/pulumi/pulumi-terraform-bridge/pull/1583 in preparation of deprecating the bridge replay.

### CODE REVIEW

**Review by iwahbe — APPROVED** [review]
This looks good to me, but we should probably wait for someone familiar with this library to approve before merging.

**Review by t0yv0 — CHANGES_REQUESTED** [review]
Hold on a sec, can you remind me where this is used? We discussed that WithUnorderedArrayPaths was actually not needed I recall.

**Comment by VenelinMartinov** [comment]
The PR where I originally introduced this is https://github.com/pulumi/pulumi-terraform-bridge/pull/1583.

The only place where `WithUnorderedArrayPaths` is used is in `replay.go:196` - the change is also in this PR.

I ended up reverting the changes to the externally used Replay - no options there and baked in the assumption of `errors` being unordered in the framework. To match that I added an option to `AssertJSONMatchesPattern`. LMK If I have misunderstood you and if you have a better suggestion on how to fix this.

**Comment by t0yv0** [comment]
Ah yes, it is used I see! Sorry for being difficult here but I find this path-based API really awkward to explain so if we can get by without that's a little win, but since it bugs me so much I guess I can put the work in to rid of it. One sec

**Comment by t0yv0** [comment]
https://github.com/pulumi/providertest/pull/61 wdyt?

**Comment by t0yv0** [comment]
Closing in favor of https://github.com/pulumi/providertest/pull/61

**Pull request closed without merging**
